payapp/urls.py
from django.urls import register_converter, path
from .views import transactions, transfer_money, \
    PaymentRequestView, NotificationView, PaymentApprovalView, PayRequestStatusView, success_view


# class FloatConverter:
#     regex = '[+-]?([0-9]*[.])?[0-9]+'
#
#     def to_python(self, value):
#         return float(value)
#
#     def to_url(self, value):
#         return str(value)
#
#
# register_converter(FloatConverter, 'float')

app_name = 'payapp'
urlpatterns = [
    path('transactions/', transactions, name='account-transactions'),
    path('transfer_money/', transfer_money, name='account-transfer_money'),
    path('request_payment/', PaymentRequestView.as_view(), name='account-request_payment'),
    path('notification/', NotificationView.as_view(), name='account-notification'),
    path('payment_approval/', PaymentApprovalView.as_view(), name='account-payment_approval'),
    path('payment_requested_status/', PayRequestStatusView.as_view(), name='account-payment_requested_status'),
    path('success/<str:action>/', success_view, name='account-success'),
    # path('conversion/<str:base>/<str:target>/<float:amount>/', conversion, name='conversion'),

]

register/urls.py
from django.urls import path
from .views import home, profile, RegisterView, dashboard, register_admin, users_list

urlpatterns = [
    path('', home, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile'),
    path('dashboard/', dashboard, name='users-dashboard'),
    path('register_admin/', register_admin, name='register_admin'),
    path('users_list/', users_list, name='users_list'),

]

webapps2024/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from register.views import CustomLoginView, ResetPasswordView, ChangePasswordView
from register.forms import LoginForm

urlpatterns = [
                  path('admin/', admin.site.urls),

                  # path('', include('register.urls', namespace='register')),
                  path('', include('register.urls')),

                  path('payapp/', include('payapp.urls')),

                  path('currency_conversion/', include('currency_conversion.urls')),

                  path('login/', CustomLoginView.as_view(redirect_authenticated_user=True,
                                                         template_name='users/login.html',
                                                         authentication_form=LoginForm), name='login'),

                  path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

                  path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

                  path('password-reset-confirm/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
                       name='password_reset_confirm'),

                  path('password-reset-complete/',
                       auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
                       name='password_reset_complete'),

                  path('password-change/', ChangePasswordView.as_view(), name='password_change'),

                  re_path(r'^oauth/', include('social_django.urls', namespace='social')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


register/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from PIL import Image


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        Profile.objects.get_or_create(user=self)

    def __str__(self):
        return self.email


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    # objects = Profile()
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # email = models.EmailField(unique=True)
    # objects = models.Manager()  # Explicitly define the objects manager
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    # balance = models.DecimalField(default=1000, max_digits=10, decimal_places=2)
    # currency_choices = [('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')]
    # default_currency = 'GBP'  # Choose your default currency here
    # currency = models.CharField(max_length=3, choices=currency_choices, default=default_currency)

    def __str__(self):
        return self.user.username

    # resizing images
    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.avatar.path)


class Account(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    balance = models.DecimalField(default=1000, max_digits=10, decimal_places=2)
    currency_choices = [('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')]
    default_currency = 'GBP'  # Choose your default currency here
    currency = models.CharField(max_length=3, choices=currency_choices, default=default_currency)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.username}"

register/views.py
from decimal import Decimal

import requests
from django.conf import settings
from register.models import CustomUser as User
# from django.contrib.auth.models import User
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.utils.decorators import method_decorator
from payapp.models import Notification
from .models import Account
from .forms import RegisterForm, LoginForm, UpdateUserForm, UpdateProfileForm, AdminRegisterForm
from django import template
from django.contrib.auth.decorators import login_required, user_passes_test


def home(request):
    return render(request, 'users/home.html')


register = template.Library()


@register.simple_tag
def unread_notification_count(user):
    return Notification.objects.filter(to_user=user, is_read=False).count()


@login_required
def dashboard(request):
    unread_notification_count = Notification.objects.filter(to_user=request.user, is_read=False).count()
    return render(request, 'users/dashboard.html', {'unread_notification_count': unread_notification_count})


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    @method_decorator(transaction.atomic)
    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save()
            # Additional data such as currency can be accessed from the form's cleaned_data
            currency = form.cleaned_data.get('currency')
            base = 'GBP'
            balance = 1000

            # the system should make the appropriate conversion to assign the right initial amount of money
            if currency != base:
                try:
                    response = requests.get(
                        f'{settings.BASE_URL}/currency_conversion/conversion/{base}/{currency}/{balance}')
                    response.raise_for_status()  # Raises a HTTPError if the response status is 4xx, 5xx
                except requests.exceptions.RequestException as e:
                    messages.error(request, f'Currency conversion API request failed: {str(e)}')
                    return render(request, self.template_name, {'form': form})
            try:
                balance = Decimal(str(response.json()['converted_amount']))
                print('acc_balance $$$$$$ -> ', balance)



            user.profile.balance = balance
            user.profile.save()
            # Create an associated account for the user
            Account.objects.create(user=user, currency=currency, balance=balance)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


# Class based view that extends from the built in login view to add a remember me functionality
class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('users-home')


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users-home')


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            # Check if email is unique
            email = user_form.cleaned_data.get('email')
            if User.objects.filter(email=email).exclude(username=request.user.username).exists():
                messages.error(request, 'Email address must be unique.')
                return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})

            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users-profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
@user_passes_test(lambda u: u.is_staff)
@user_passes_test(lambda u: u.is_superuser)
def register_admin(request):
    form_class = AdminRegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register_admin.html'

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_superuser = True
            user.save()
            user.profile.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Admin account created for {username}')
        return render(request, template_name, {'form': form})
    else:
        form = form_class(initial=initial)
        return render(request, template_name, {'form': form})


@login_required
@user_passes_test(lambda u: u.is_staff)
@user_passes_test(lambda u: u.is_superuser)
def users_list(request):
    users = User.objects.all()
    return render(request, 'users/users_list.html', {'users': users})


templates/users/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a href="/" class="navbar-brand">Home</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                    <a href="{% url 'users-profile' %}" class="nav-item nav-link">Profile</a>
                    <a href="{% url 'users-dashboard' %}" class="nav-item nav-link">Dashboard</a>
                      <form method="post" action="{% url 'logout' %}">
                          {% csrf_token %}
                          <button type="submit" class="nav-item nav-link btn btn-danger">
                              Logout
                          </button>
                      </form>
                  {% else %}
                    <a href="{% url 'login' %}" class="nav-item nav-link">Sign in</a>
                  {% endif %}

                </div>
            </div>
        </nav>
        <!--Any flash messages pop up in any page because this is the base template-->
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- A plugin for password show/hide  -->
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

</body>
</html>

templates/users/dashboard.html
{% extends "users/base.html" %}

{% block title %} Dashboard {% endblock title %}

{% block content %}

    {% if request.user.is_superuser %}
        <br>
        <div class="card actions-card shadow">
            <div class="card-header bg-primary text-white">
                <h5 class="mb-0">Actions</h5>
            </div>
            <div class="card-body d-flex justify-content-around">

                <!-- Create Admin Action -->
                <div class="action-item">
                    <a href="{% url 'register_admin' %}" class="action-link">
                        <div class="icon-container">
                            <i class="fas fa-user-plus"></i>
                        </div>
                        <span class="action-title">Create Admin</span>
                    </a>
                </div>

                <!-- See All Registered Users Action -->
                <div class="action-item">
                    <a href="{% url 'users_list' %}" class="action-link">
                        <div class="icon-container">
                            <i class="fas fa-users"></i>
                        </div>
                        <span class="action-title">See All Registered Users</span>
                    </a>
                </div>


                <div class="action-item">
                    <a href="{% url 'payapp:account-transactions' %}" class="action-link">
                        <div class="icon-container">
                            <i class="fas fa-money-check-alt"></i>
                        </div>
                        <span class="action-title">See All Transactions</span>
                    </a>
                </div>

                <div class="action-item">
                    <a href="{% url 'payapp:account-payment_requested_status' %}" class="action-link">
                        <div class="icon-container">
                            <i class="fas fa-file-invoice-dollar"></i>
                        </div>
                        <span class="action-title">See All Requests</span>
                    </a>
                </div>
            </div>
        </div>

    {% else %}
        <div class="container my-5">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <!-- Account Balance Card -->
                    <div class="card balance-card mb-4 shadow-sm">
                        <div class="card-body">
                            <h3 class="card-title">Account Balance</h3>
                            <p class="balance-amount lead">
                                {% if user.account.currency == 'GBP' %}
                                    £{{ user.account.balance }}
                                {% elif user.account.currency == 'USD' %}
                                    ${{ user.account.balance }}
                                {% elif user.account.currency == 'EUR' %}
                                    €{{ user.account.balance }}
                                {% else %}
                                    {{ user.account.balance }} {{ user.account.currency }}
                                {% endif %}
                            </p>
                        </div>
                    </div>

                    <!-- Quick Actions Card -->
                    <div class="card actions-card shadow">
                        <div class="card-header bg-primary text-white">
                            <h5 class="mb-0">Actions</h5>
                        </div>
                        <div class="card-body d-flex justify-content-around">
                            <!-- Transfer Money Action -->
                            <div class="action-item">
                                <a href="{% url 'payapp:account-transfer_money' %}" class="action-link">
                                    <div class="icon-container">
                                        <i class="fas fa-exchange-alt"></i>
                                    </div>
                                    <span class="action-title">Transfer Money</span>
                                </a>
                            </div>

                            <!-- Request Payment Action -->
                            <div class="action-item">
                                <a href="{% url 'payapp:account-request_payment' %}" class="action-link">
                                    <div class="icon-container">
                                        <i class="fas fa-hand-holding-usd"></i>
                                    </div>
                                    <span class="action-title">Request Payment</span>
                                </a>
                            </div>

                            <!-- Notifications Action -->
                            <div class="action-item">
                                <a href="{% url 'payapp:account-notification' %}" class="action-link">
                                    <div class="icon-container">
                                        <i class="fas fa-bell"></i>
                                        {% if unread_notification_count > 0 %}
                                            <span class="notification-count">{{ unread_notification_count }}</span>
                                        {% endif %}
                                    </div>
                                    <span class="action-title">Notifications</span>
                                </a>
                            </div>

                            <div class="action-item">
                                <a href="{% url 'payapp:account-transactions' %}" class="action-link">
                                    <div class="icon-container">
                                        <i class="fas fa-money-check-alt"></i>
                                    </div>
                                    <span class="action-title">Transactions</span>
                                </a>
                            </div>

                            <div class="action-item">
                                <a href="{% url 'payapp:account-payment_requested_status' %}" class="action-link">
                                    <div class="icon-container">
                                        <i class="fas fa-file-invoice-dollar"></i>
                                    </div>
                                    <span class="action-title">Request Status</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <style>

        .actions-card {
            border-radius: 0.75rem;
            background: #f8f9fa;
        }

        .action-item {
            flex-grow: 1;
            text-align: center;
        }

        .action-link {
            display: block;
            padding: 15px;
            border-radius: 0.5rem;
            transition: background-color 0.3s ease;
            color: #333;
            text-decoration: none;
        }

        .action-link:hover {
            background-color: #e2e6ea;
        }

        .icon-container {
            font-size: 2rem;
            margin-bottom: 8px;
        }

        .action-title {
            display: block;
            font-weight: bold;
        }

        .fas {
            margin-bottom: 5px;
        }

        .balance-card, .actions-card {
            border-radius: 0.75rem;
        }

        .balance-amount {
            font-size: 2rem;
            font-weight: bold;
        }

        .btn-action {
            margin-right: 0.5rem;
            margin-bottom: 0.5rem;
        }

        .btn-primary {
            background-color: #0056b3;
            border-color: #004085;
        }

        .btn-primary:hover {
            background-color: #004085;
            border-color: #003366;
        }

        .btn-secondary {
            background-color: #6c757d;
            border-color: #545b62;
        }

        .btn-secondary:hover {
            background-color: #545b62;
            border-color: #4e555b;
        }

        .btn-success {
            background-color: #28a745;
            border-color: #218838;
        }

        .btn-success:hover {
            background-color: #218838;
            border-color: #1e7e34;
        }
        .notification-count {
            position: absolute;
            top: 0;
            right: 0;
            background-color: #dc3545;
            color: white;
            font-size: 12px;
            padding: 2px 6px;
            border-radius: 50%;
        }

    </style>
{% endblock content %}

templates/users/home.html
{% extends "users/base.html" %}
{% block title %} Home Page {% endblock title%}
{% block content %}
    <br>
    <div class="jumbotron">
        <h1 class="display-4">Welcome, {{user.first_name.title|default:'Guest'}}</h1>
        <h4>Send, Receive, and Spend Money Securely with PayPal</h4>
        <p>Join over 350 million users worldwide!</p>
        <p class="lead">
            This is <b>user registration and login system</b>
        </p>
        <hr class="my-4">
        <p class="lead">
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary btn-lg">
                        Logout
                    </button>
                </form>
            {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">Sign in</a>
            {% endif %}
        </p>
    </div>

{% endblock content %}

templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address.
        </p>
        <br><hr><a href="{% url 'login' %}" class="btn btn-primary">Sign in again</a>
        </div>
    </div>


{% endblock content %}

templates/users/password_reset.html
{% extends "users/base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                        	<div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users-register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}